
import { Inter } from 'next/font/google'
import './globals.css'
import { Metadata } from 'next'


export const metadata: Metadata = {
  title: 'JS Mastery Pro',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='min-h-screen bg-black-100 font-poppins'>{children}</body>
    </html>
  )
}
